# Generated by Django 4.0.1 on 2022-01-07 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='registrationDate',
            new_name='registration_date',
        ),
    ]
